Add rename button in all projects page
microsoft/pxt pull request #10017
Opened 2024-05-22 08:31 UTC by sae220

splitted from https://github.com/microsoft/pxt/pull/10016

2024-05-23 16:17 UTC, riknoll requested changes

2024-05-23 16:17 UTC, riknoll commented on webapp/src/workspace.ts
> +        .then(() => newHdr)
```suggestion
    await importAsync(newHdr, dupText);
    return newHdr;
```

2024-05-23 16:17 UTC, riknoll commented on webapp/src/scriptmanager.tsx
> +    async handleRename() {
```suggestion
    async handleRename() {
        pxt.tickEvent("scriptmanager.rename", undefined, { interactiveConsent: true });
```

2024-05-25 13:13 UTC, sae220 commented
@riknoll I don't know how pxt.tickEvent function works. Could you let me know briefly?

2024-06-03 18:37 UTC, riknoll approved these changes

2024-06-03 18:48 UTC, riknoll commented
@sae220 LGTM! lint is failing because of trailing whitespace. you can run the lint locally with `gulp lint`

2024-06-04 16:18 UTC, riknoll commented
@sae220 we don't have a docker container or anything like that, but we have people who work on Windows, Linux, and MacOS on the team so they should all work fine! I personally use Ubuntu on WSL, and that's what I would recommend if you're on Windows

2024-06-04 16:26 UTC, merged

2024-06-04 16:46 UTC, sae220 commented
@riknoll 
OK. I'll use Ubuntu on WSL.

Can I cherry pick this for stable9.3? As I said before, we can't rename projects in pxt-minecraft now.

2024-06-04 16:47 UTC, riknoll commented
please do! tag me in the PR